version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8080/api

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/your_database_name
      SPRING_DATASOURCE_USERNAME: your_mysql_username
      SPRING_DATASOURCE_PASSWORD: your_mysql_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: